import { Ticket, User } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 1,
    name: 'Priya Patel',
    email: 'priya.patel@helpdesk.example.com',
    created_at: '2026-09-10T08:00:00Z',
  },
  {
    id: 2,
    name: 'Marcus Chen',
    email: 'marcus.chen@helpdesk.example.com',
    created_at: '2026-09-11T09:30:00Z',
  },
  {
    id: 3,
    name: 'Sarah Miller',
    email: 'sarah.miller@helpdesk.example.com',
    created_at: '2026-09-12T11:00:00Z',
  },
  {
    id: 4,
    name: 'Alex Rivera',
    email: 'alex.rivera@helpdesk.example.com',
    created_at: '2026-09-13T14:15:00Z',
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 1,
    customer_name: 'Alice Johnson',
    customer_email: 'alice@example.com',
    title: 'VPN connection dropping intermittently',
    description: 'Cannot sustain connection to internal staging servers from home office. Disconnects every 10 minutes.',
    priority: 'urgent',
    status: 'open',
    created_at: '2026-09-16T08:00:00Z',
    due_at: '2026-09-16T10:00:00Z',
    updated_at: '2026-09-16T08:30:00Z',
    assigned_to: 1,
    assignee: INITIAL_USERS[0],
    overdue: true,
  },
  {
    id: 2,
    customer_name: 'Robert Davis',
    customer_email: 'robert.d@globex.org',
    title: 'Production database read replica latency spike',
    description: 'Read replica replication lag exceeded 300s alert threshold. Queries timing out.',
    priority: 'urgent',
    status: 'in_progress',
    created_at: '2026-09-16T08:30:00Z',
    due_at: '2026-09-16T10:30:00Z',
    updated_at: '2026-09-16T09:15:00Z',
    assigned_to: null,
    assignee: null,
    overdue: true,
  },
  {
    id: 3,
    customer_name: 'Emily Watson',
    customer_email: 'emily.w@acme.corp',
    title: 'SSO login loop on partner portal',
    description: 'Staff members are trapped in authentication redirect loop when signing in via Okta.',
    priority: 'urgent',
    status: 'open',
    created_at: '2026-09-16T09:30:00Z',
    due_at: '2026-09-16T11:30:00Z',
    updated_at: '2026-09-16T09:30:00Z',
    assigned_to: null,
    assignee: null,
    overdue: false,
  },
  {
    id: 4,
    customer_name: 'Michael Chang',
    customer_email: 'mchang@techstart.io',
    title: 'Payroll export script missing column headers',
    description: 'Monthly CSV export for accounting team does not include tax jurisdiction column.',
    priority: 'normal',
    status: 'open',
    created_at: '2026-09-15T10:00:00Z',
    due_at: '2026-09-16T10:00:00Z',
    updated_at: '2026-09-15T11:00:00Z',
    assigned_to: 2,
    assignee: INITIAL_USERS[1],
    overdue: true,
  },
  {
    id: 5,
    customer_name: 'Sophia Loren',
    customer_email: 'sophia@creativehub.co',
    title: 'Request for secondary monitor and ergonomic keyboard',
    description: 'New design hire onboarding kit hardware requisition request.',
    priority: 'normal',
    status: 'open',
    created_at: '2026-09-16T07:00:00Z',
    due_at: '2026-09-17T07:00:00Z',
    updated_at: '2026-09-16T07:00:00Z',
    assigned_to: 3,
    assignee: INITIAL_USERS[2],
    overdue: false,
  },
  {
    id: 6,
    customer_name: 'David Kim',
    customer_email: 'david.kim@enterprise.net',
    title: 'API rate limits triggered unexpectedly on webhook worker',
    description: 'Batch sync worker hitting HTTP 429 errors from partner inventory endpoint.',
    priority: 'urgent',
    status: 'in_progress',
    created_at: '2026-09-16T09:00:00Z',
    due_at: '2026-09-16T11:00:00Z',
    updated_at: '2026-09-16T09:40:00Z',
    assigned_to: 1,
    assignee: INITIAL_USERS[0],
    overdue: false,
  },
  {
    id: 7,
    customer_name: 'Carlos Mendez',
    customer_email: 'cmendez@logistics.com',
    title: 'Warehouse scanner handheld firmware update failed',
    description: 'Unit #4 displays bootloader error following overnight OTA patch.',
    priority: 'normal',
    status: 'open',
    created_at: '2026-09-16T06:00:00Z',
    due_at: '2026-09-17T06:00:00Z',
    updated_at: '2026-09-16T06:00:00Z',
    assigned_to: null,
    assignee: null,
    overdue: false,
  },
  {
    id: 8,
    customer_name: 'Hannah Abbott',
    customer_email: 'hannah@retailpartners.uk',
    title: 'Billing portal invoice breakdown PDF corrupt',
    description: 'Generated PDF invoice for August cycle has zero byte size upon download.',
    priority: 'normal',
    status: 'resolved',
    created_at: '2026-09-14T14:00:00Z',
    due_at: '2026-09-15T14:00:00Z',
    updated_at: '2026-09-15T13:45:00Z',
    assigned_to: 3,
    assignee: INITIAL_USERS[2],
    overdue: false,
  },
  {
    id: 9,
    customer_name: 'Oliver Queen',
    customer_email: 'oliver@starling.com',
    title: 'Security group audit for external consultant access',
    description: 'Quarterly review of third-party contractor SSH keys and IAM role attachments.',
    priority: 'normal',
    status: 'closed',
    created_at: '2026-09-13T10:00:00Z',
    due_at: '2026-09-14T10:00:00Z',
    updated_at: '2026-09-14T16:20:00Z',
    assigned_to: 2,
    assignee: INITIAL_USERS[1],
    overdue: false,
  },
];
